apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: investigator-ai
spec:
  type: NodePort
  selector:
    app: investigator-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
