qdrant.host=localhost
qdrant.port=6333
qdrant.default-collection=documents
qdrant.embedding-model=mlx-community/nomicai-modernbert-embed-base-bf16
qdrant.embedding-base-url=http://host.minikube.internal:8082/v1
