apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langfuse-clickhouse-pvc
  namespace: investigator-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
