apiVersion: v1
kind: Service
metadata:
  name: langfuse-postgres
  namespace: investigator-ai
spec:
  type: ClusterIP
  selector:
    app: langfuse-postgres
  ports:
    - port: 5432
      targetPort: 5432
